### ISSUE TITLE
Tag 1 (Sebnitz->Malevil)

### ISSUE THREAD

**Issue by splosch** [splosch/transost_log#1]
https://www.komoot.de/tour/1287285358

60,0 km
1 300 hm

![Screenshot_20230902-110612_Komoot.jpg](https://github.com/splosch/transost_log/assets/666934/9bda0558-4f3c-4011-98df-a00c543611c2)

**Comment by splosch** [comment]
Wir haben gefrühstückt, gepackt und aufgerödelt.

Das Team "Karl-Marx-Stadt" hat sich am 2.9.2023 8:00 im der Rößlerstr. Getroffen.

Christian und Sebastian haben bei Peter übernachtet. Mario ist früh dann mit Brötchen dazugestossen.

Gegen 9:30 waren alle Räder am Auto und nach letzten Abstimmungen, zu wer nimmt wieviel Wasser mit und welches Werkzeug, wieviel Druck. wer muss sich für sein Rad schämen ;)... waren wir abfahrtbereit.

![20230902_095839.jpg](https://github.com/splosch/transost_log/assets/666934/52b846e9-b751-4cba-af35-cafadc252021)

**Comment by splosch** [comment]
Leider schon die erste trübende Nachricht. Thomas ist erkältet und hofft am Montag dazustoßen zu können.

**Comment by splosch** [comment]
Da ein Rucksack zurückgelassen wurde... lieber nochmal alles durchzählen

![20230902_100401.jpg](https://github.com/splosch/transost_log/assets/666934/0e86dff6-bf01-4107-ae3d-d14ca9013b79)

![20230902_100503.jpg](https://github.com/splosch/transost_log/assets/666934/7dc619a1-9bdc-4152-bec2-a4d88d3d3989)

**Comment by splosch** [comment]
Nach 12km / 350hm der Erste Aussichtstopp![20230902_132212.jpg](https://github.com/splosch/transost_log/assets/666934/e8526a00-b3d3-4ed1-8e32-59ecb35d2ffa)

Allerdings sind es noch 50km und es ist schon 13:30...

**Comment by splosch** [comment]
12km Togo, aber vorher Gestank tanken.
Knoblauch-Zuppa - Beste!
Knoblauchscore 12 von 10 :)
![20230902_175930.jpg](https://github.com/splosch/transost_log/assets/666934/9a43094d-92f2-405e-a60c-c2117c9367a2)

**Comment by BeWi60** [comment]
Na Jungs, mit der Knobi- soup wirds aber werden.
Ich wünsch Euch was, vorallem Spassss und keine Rippenbrüche.

**Comment by splosch** [comment]
**Fazit erste Etappe:**
- Ankunft im Resort Malevil ca. 19:30 
nach etwas Suchen der Unterkunft  
- Keine Verletzungen *ausser emotionale 
- Keine nennenswerten Stürze.
- Alle Räder heile
- 

Wir sind sehr spät auf der Runde in die erste Pause gekommen, das hat etwas die Stimmung bestimmt. Und die letzten 3km waren gut schlammig.

**Ein Highlight**
Der Weg auf die Lausche hoch war hart, und nur Sebastian hat den Anstieg technisch und konditionel zu 98% geschafft. Wir Normalos mussten schieben. 
Er hat aber auch doppelt so massive Waden wie wir :)




![IMG-20230902-WA0014.jpg](https://github.com/splosch/transost_log/assets/666934/31d89c35-481a-42f5-904b-2870966ac5bc)

Wir sind da. Un es gibt Bier.

![IMG-20230902-WA0016.jpg](https://github.com/splosch/transost_log/assets/666934/134bf430-32f4-4e69-aa00-29ad719994d8)

![IMG-20230902-WA0020.jpg](https://github.com/splosch/transost_log/assets/666934/c04bdcb1-cc6e-4f87-9cf9-8029ed04567c)
